### ISSUE TITLE
Change contact form title

### ISSUE THREAD

**Issue by kylemclaren** [kylemclaren/covidcheck.co.za#14]
https://github.com/kylemclaren/covidcheck.co.za/blob/master/dist/contact.html#L7

**Comment by yonis9** [comment]
Hi, what is the new title you want to replace?

**Comment by kylemclaren** [comment]
@yonis9 Hi 👋 `COVID Check - Contact Us` would do I think

**Comment by yonis9** [comment]
@kylemclaren  OK, I'll take it
